Добавила методы в сервис Person и соответствующие контроллеры
Jarilo-Products/pet-shelter-bot pull request #11
Opened 2023-06-12 20:26 UTC by OlgaJav22

Созданы эндпоинты и соответствующие методы:
- получение всех волонтеров (GET /volunteers) – без параметров
- установка статуса волонтера (is_volunteer = true) по id персоны (PATCH /volunteers/{id})
    - получение всех персон (GET /persons) – без параметров
- отозвание статуса волонтера (is_volunteer = false) по id персоны (PATCH /volunteers/{id}/revoke)

2023-06-13 11:06 UTC, safgbad requested changes

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            summary = "Получаем всех людей.",
здесь путь можно не писать

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            ),
тут лучше 204 код – no content
он возвращается без тела

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +        }
здесь соответственно не badRequest, а noContent()

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            summary = "Получаем всех волентеров.",
лучше просто "/volunteers"

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            ),
тоже 204 код лучше

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            return ResponseEntity.badRequest().build();
тоже noContent() вместо badRequest()

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +            return ResponseEntity.ok().build();
тут никак не проверяется наличие персоны с таким id в базе
можно это сделать на уровне сервиса
```java
if (Objects.equals(person.getId(), id) && personService.setPersonIsVolunteerIsTrue(id)) {
  return ResponseEntity.ok().build();
} else {
  return ResponseEntity.notFound().build();
}
```

в changeIsVolunteerIsFalse то же самое

2023-06-13 11:06 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/service/PersonService.java
> +    }
пускай метод возвращает boolean: true если пользователь нашелся и false – если нет
соответственно
```java
public boolean setPersonIsVolunteerIsTrue(Long id) {
  Person person = personRepository.findPersonById(id);
  if (person == null) {
    return false;
  }
  person.setIsVolunteer(true);
  personRepository.save(person);
  return true;
}
```
метод setPersonIsVolunteerIsFalse аналогично

2023-06-13 19:13 UTC, OlgaJav22 commented on backend/src/main/java/pro/sky/petshelterbot/service/PersonService.java
> +    }
Готово!

2023-06-14 16:56 UTC, safgbad requested changes
в одном месте забыла исправить после копирования

2023-06-14 16:56 UTC, safgbad commented on backend/src/main/java/pro/sky/petshelterbot/controllers/PersonController.java
> +        if (Objects.equals(person.getId(), id) && personService.setPersonIsVolunteerIsTrue(id)) {
тут название метода надо поменять: setPersonIsVolunteerIs**False**

2023-06-16 14:43 UTC, safgbad approved these changes

2023-06-17 09:23 UTC, LoliPis approved these changes

2023-06-17 09:40 UTC, merged